name: Linter

on: pull_request

jobs:
  lint:
    name: Dart Analyze Linter
    runs-on: ubuntu-latest
    container:
      image:  cirrusci/flutter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: flutter pub get
      - name: Run Dart Analyze
        run: dart analyze ${{ github.action_path }}
