name: Tests

on: pull_request

jobs:
  test:
    name: Dart Test
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: flutter pub get
      - name: Run Dart Tests
        run: dart test
